[TestFix] Fix Configure client test failure
Problem:
The Pacific suite ceph_volume/tier-2-ceph-volume
was failing with AttributeError: 'NoneType' object
has no attribute 'distro_info'

Fix:
The reason of this issue is that from the test client5
is being called, where as the conf has only 4 nodes.
So marking the client4 in test will resolve the issue

Signed-off-by: Pranav Prakash <prprakas@redhat.com>