LooseVersion requies string or bytes like object
An earlier check introduced for license acceptance broke when
the release version is a non-string. This happens when it is
provided from the test data.

Converting the release version to string helps here.

```
Traceback (most recent call last):
  File "/data/jenkins/ceph-builds/IBM/9.0/rhel-10/upgrade/20.1.0-162/rados/6/cephci/tests/ceph_installer/test_cephadm.py", line 172, in run
    func(cfg)
  File "/data/jenkins/ceph-builds/IBM/9.0/rhel-10/upgrade/20.1.0-162/rados/6/cephci/ceph/ceph_admin/bootstrap.py", line 372, in bootstrap
    if manifest_obj.product == "ibm" and LooseVersion(
  File "/data/jenkins/ceph-builds/IBM/9.0/rhel-10/upgrade/20.1.0-162/rados/6/cephci/.venv/lib64/python3.9/site-packages/looseversion/__init__.py", line 142, in __init__
    self.parse(vstring)
  File "/data/jenkins/ceph-builds/IBM/9.0/rhel-10/upgrade/20.1.0-162/rados/6/cephci/.venv/lib64/python3.9/site-packages/looseversion/__init__.py", line 179, in parse
    components = [x for x in self.component_re.split(vstring) if x and x != "."]
TypeError: expected string or bytes-like object

```

In this commit, we are ensuring the release is a string when passed to
LooseVersion.

Signed-off-by: Pragadeeswaran Sathyanarayanan <pragadeeswaran.sathyanarayanan@ibm.com>