Fix unboundlocal error observed with collect_ceph_logs
A recent introduction of collecting the logs or coredump variables
did not have a default value. Hence, when an user does not provide
them, it would cause the below traceback

```
Traceback (most recent call last):
  File "/data/jenkins/ceph-builds/IBM/8.1/rhel-9/regression/19.2.1-374/cephfs/18/cephci/run.py", line 1365, in <module>
    rc = run(args)
  File "/data/jenkins/ceph-builds/IBM/8.1/rhel-9/regression/19.2.1-374/cephfs/18/cephci/run.py", line 1296, in run
    if jenkins_rc or collect_ceph_logs:
UnboundLocalError: local variable 'collect_ceph_logs' referenced before assignment
script returned exit code 1
```

Signed-off-by: Pragadeeswaran Sathyanarayanan <pragadeeswaran.sathyanarayanan@ibm.com>